### ISSUE TITLE
Cosmetic Fixes

### ISSUE THREAD

**Issue by Shtoyan** [theengineertcr/KFOldSchoolZeds#3]
Ola! Just a few cosmetic fixes that i suggest to make the repo more user friendly and easier to surf.

0. Add a License. If you don't care at all you can choose MIT. Otherwise GPLv3 will suit fine.
1. Add your Steam Workshop link to "About" section. And Github link to Workshop, why not.
2. Add topics so people can find it from global search more easily. @Vel-San and I use the same ones, if you are interested:
    - unrealscript
    - mutator
    - killing-floor
    - greylisted
3. You can hide "Packages" section. And "Actions", "Projects", "Wiki" if you are not going to use them.

**Comment by theengineertcr** [comment]
Hi! Thanks for the heads up and suggestions. 

I'll add the first 3, although I'm not sure how to go about the last one. I've managed to hide the Wiki and Actions, but I don't see an option under settings for the others unless if I've missed it.

Cheers!

**Comment by theengineertcr** [comment]
All done, thanks again!
